### ISSUE TITLE
datecmp 기반 기술 조사

### ISSUE THREAD

**Issue by hnym1104** [0binn/Project2#20]
struct tm* localtime은 시 정보가 들어가는 구조체 포인터로, 구조체 변수인 tm_mon, tm_mday를 이용해 각 파일의 date를 비교할 수 있습니다.

**Comment by doomdabo** [comment]
struct tm* localtime은 시 정보가 들어가는 구조체 포인터로, 구조체 변수인 tm_mon, tm_mday를 이용해 각 파일의 date를 비교할 수 있습니다.
